In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/train.csv')

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
age_mean_value=df['Age'].mean()
df['Age']=df['Age'].fillna(age_mean_value)

In [ ]:
df.tail(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
 df.drop("Cabin",axis=1,inplace=True)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [ ]:
filtered_age = df[df.Age>40]
filtered_age

sorted_passengers= df.sort_values('Name',ascending=True,kind = 'heapsort')

sorted_passengers.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,S
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C
365,366,0,3,"Adahl, Mr. Mauritz Nils Martin",male,30.0,0,0,C 7076,7.2500,S
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,S
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,C

In [ ]:
merged_df=pd.merge(df.head(2),df.tail(2),how='outer',indicator=True)
merged_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,_merge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,left_only
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,left_only
2,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,right_only
3,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,right_only

In [ ]:
group_df = df.groupby('Name')

for key,item in group_df:
  print(group_df.get_group(key),"\n\n")

Streaming output truncated to the last 5000 lines.
     Parch      Ticket  Fare Cabin Embarked
671      0  F.C. 12750  52.0   B71        S


     PassengerId  Survived  Pclass                            Name   Sex  Age  \
549          550         1       2  Davies, Master. John Morgan Jr  male  8.0

     SibSp  Parch      Ticket   Fare Cabin Embarked
549      1      1  C.A. 33112  36.75   NaN        S


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
565          566         0       3  Davies, Mr. Alfred J  male  24.0      2

     Parch     Ticket   Fare Cabin Embarked
565      0  A/4 48871  24.15   NaN        S


     PassengerId  Survived  Pclass                       Name   Sex   Age  \
385          386         0       2  Davies, Mr. Charles Henry  male  18.0

     SibSp  Parch        Ticket  Fare Cabin Embarked
385      0      0  S.O.C. 14879  73.5   NaN        S


     PassengerId  Survived  Pclass               Name     Sex   Age  SibSp  \
635          636         1       2  Davis, Miss. Mary  female  28.0      0

     Parch  Ticket  Fare Cabin Embarked
635      0  237668  13.0   NaN        S


     PassengerId  Survived  Pclass                                       Name  \
347          348         1       3  Davison, Mrs. Thomas Henry (Mary E Finck)

        Sex  Age  SibSp  Parch  Ticket  Fare Cabin Embarked
347  female  NaN      1      0  386525  16.1   NaN        S


     PassengerId  Survived  Pclass                        Name   Sex  Age  \
788          789         1       3  Dean, Master. Bertram Vere  male  1.0

     SibSp  Parch     Ticket    Fare Cabin Embarked
788      1      2  C.A. 2315  20.575   NaN        S


    PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
93           94         0       3  Dean, Mr. Bertram Frank  male  26.0      1

    Parch     Ticket    Fare Cabin Embarked
93      2  C.A. 2315  20.575   NaN        S


     PassengerId  Survived  Pclass                Name   Sex  Age  SibSp  \
335          336         0       3  Denkoff, Mr. Mitto  male  NaN      0

     Parch  Ticket    Fare Cabin Embarked
335      0  349225  7.8958   NaN        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
320          321         0       3  Dennis, Mr. Samuel  male  22.0      0

     Parch     Ticket  Fare Cabin Embarked
320      0  A/5 21172  7.25   NaN        S


    PassengerId  Survived  Pclass                           Name     Sex  \
44           45         1       3  Devaney, Miss. Margaret Delia  female

     Age  SibSp  Parch  Ticket    Fare Cabin Embarked
44  19.0      0      0  330958  7.8792   NaN        Q


     PassengerId  Survived  Pclass                     Name   Sex   Age  \
690          691         1       1  Dick, Mr. Albert Adrian  male  31.0

     SibSp  Parch Ticket  Fare Cabin Embarked
690      1      0  17474  57.0   B20        S


     PassengerId  Survived  Pclass                                       Name  \
781          782         1       1  Dick, Mrs. Albert Adrian (Vera Gillespie)

        Sex   Age  SibSp  Parch Ticket  Fare Cabin Embarked
781  female  17.0      1      0  17474  57.0   B20        S


     PassengerId  Survived  Pclass              Name   Sex   Age  SibSp  \
349          350         0       3  Dimic, Mr. Jovan  male  42.0      0

     Parch  Ticket    Fare Cabin Embarked
349      0  315088  8.6625   NaN        S


     PassengerId  Survived  Pclass                       Name   Sex  Age  \
445          446         1       1  Dodge, Master. Washington  male  4.0

     SibSp  Parch Ticket     Fare Cabin Embarked
445      0      2  33638  81.8583   A34        S


     PassengerId  Survived  Pclass                 Name   Sex  Age  SibSp  \
568          569         0       3  Doharr, Mr. Tannous  male  NaN      0

     Parch Ticket    Fare Cabin Embarked
568      0   2686  7.2292   NaN        C


     PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  \
651          652         1       2  Doling, Miss. Elsie  female  18.0      0

     Parch  Ticket  Fare Cabin Embarked
651      1  231919  23.0   NaN        S


    PassengerId  Survived  Pclass                                  Name  \
98           99         1       2  Doling, Mrs. John T (Ada Julia Bone)

       Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked
98  female  34.0      0      1  231919  23.0   NaN        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
890          891         0       3  Dooley, Mr. Patrick  male  32.0      0

     Parch  Ticket  Fare Cabin Embarked
890      0  370376  7.75   NaN        Q


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
283          284         1       3  Dorking, Mr. Edward Arthur  male  19.0

     SibSp  Parch      Ticket  Fare Cabin Embarked
283      0      0  A/5. 10482  8.05   NaN        S


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
544          545         0       1  Douglas, Mr. Walter Donald  male  50.0

     SibSp  Parch    Ticket     Fare Cabin Embarked
544      1      0  PC 17761  106.425   C86        C


    PassengerId  Survived  Pclass                      Name     Sex   Age  \
79           80         1       3  Dowdell, Miss. Elizabeth  female  30.0

    SibSp  Parch  Ticket    Fare Cabin Embarked
79      0      0  364516  12.475   NaN        S


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
582          583         0       2  Downton, Mr. William James  male  54.0

     SibSp  Parch Ticket  Fare Cabin Embarked
582      0      0  28403  26.0   NaN        S


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
130          131         0       3  Drazenoic, Mr. Jozef  male  33.0      0

     Parch  Ticket    Fare Cabin Embarked
130      0  349241  7.8958   NaN        C


     PassengerId  Survived  Pclass  \
416          417         1       2

                                                Name     Sex   Age  SibSp  \
416  Drew, Mrs. James Vivian (Lulu Thorne Christian)  female  34.0      1

     Parch Ticket  Fare Cabin Embarked
416      1  28220  32.5   NaN        S


     PassengerId  Survived  Pclass              Name   Sex   Age  SibSp  \
280          281         0       3  Duane, Mr. Frank  male  65.0      0

     Parch  Ticket  Fare Cabin Embarked
280      0  336439  7.75   NaN        Q


     PassengerId  Survived  Pclass  \
556          557         1       1

                                                  Name     Sex   Age  SibSp  \
556  Duff Gordon, Lady. (Lucille Christiana Sutherl...  female  48.0      1

     Parch Ticket  Fare Cabin Embarked
556      0  11755  39.6   A16        C


     PassengerId  Survived  Pclass  \
599          600         1       1

                                             Name   Sex   Age  SibSp  Parch  \
599  Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")  male  49.0      1      0

       Ticket     Fare Cabin Embarked
599  PC 17485  56.9292   A20        C


     PassengerId  Survived  Pclass                          Name     Sex  \
866          867         1       2  Duran y More, Miss. Asuncion  female

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked
866  27.0      1      0  SC/PARIS 2149  13.8583   NaN        C


     PassengerId  Survived  Pclass                            Name   Sex  \
675          676         0       3  Edvardsson, Mr. Gustaf Hjalmar  male

      Age  SibSp  Parch  Ticket   Fare Cabin Embarked
675  18.0      0      0  349912  7.775   NaN        S


     PassengerId  Survived  Pclass                          Name   Sex   Age  \
658          659         0       2  Eitemiller, Mr. George Floyd  male  23.0

     SibSp  Parch Ticket  Fare Cabin Embarked
658      0      0  29751  13.0   NaN        S


     PassengerId  Survived  Pclass                    Name   Sex   Age  SibSp  \
764          765         0       3  Eklund, Mr. Hans Linus  male  16.0      0

     Parch  Ticket   Fare Cabin Embarked
764      0  347074  7.775   NaN        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
129          130         0       3  Ekstrom, Mr. Johan  male  45.0      0

     Parch  Ticket   Fare Cabin Embarked
129      0  347061  6.975   NaN        S


     PassengerId  Survived  Pclass             Name   Sex  Age  SibSp  Parch  \
773          774         0       3  Elias, Mr. Dibo  male  NaN      0      0

    Ticket   Fare Cabin Embarked
773   2674  7.225   NaN        C


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
532          533         0       3  Elias, Mr. Joseph Jr  male  17.0      1

     Parch Ticket    Fare Cabin Embarked
532      1   2690  7.2292   NaN        C


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
352          353         0       3  Elias, Mr. Tannous  male  15.0      1

     Parch Ticket    Fare Cabin Embarked
352      1   2695  7.2292   NaN        C


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
592          593         0       3  Elsbury, Mr. William James  male  47.0

     SibSp  Parch    Ticket  Fare Cabin Embarked
592      0      0  A/5 3902  7.25   NaN        S


     PassengerId  Survived  Pclass                           Name     Sex  \
777          778         1       3  Emanuel, Miss. Virginia Ethel  female

     Age  SibSp  Parch  Ticket    Fare Cabin Embarked
777  5.0      0      0  364516  12.475   NaN        S


    PassengerId  Survived  Pclass                     Name   Sex  Age  SibSp  \
26           27         0       3  Emir, Mr. Farred Chehab  male  NaN      0

    Parch Ticket   Fare Cabin Embarked
26      0   2631  7.225   NaN        C


     PassengerId  Survived  Pclass                           Name     Sex  \
716          717         1       1  Endres, Miss. Caroline Louise  female

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked
716  38.0      0      0  PC 17757  227.525   C45        C


     PassengerId  Survived  Pclass                            Name     Sex  \
496          497         1       1  Eustis, Miss. Elizabeth Mussey  female

      Age  SibSp  Parch Ticket     Fare Cabin Embarked
496  54.0      1      0  36947  78.2667   D20        C


     PassengerId  Survived  Pclass                       Name   Sex   Age  \
228          229         0       2  Fahlstrom, Mr. Arne Jonas  male  18.0

     SibSp  Parch  Ticket  Fare Cabin Embarked
228      0      0  236171  13.0   NaN        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
525          526         0       3  Farrell, Mr. James  male  40.5      0

     Parch  Ticket  Fare Cabin Embarked
525      0  367232  7.75   NaN        Q


     PassengerId  Survived  Pclass                Name   Sex  Age  SibSp  \
527          528         0       1  Farthing, Mr. John  male  NaN      0

     Parch    Ticket      Fare Cabin Embarked
527      0  PC 17483  221.7792   C95        S


    PassengerId  Survived  Pclass  \
53           54         1       2

                                                 Name     Sex   Age  SibSp  \
53  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1

    Parch Ticket  Fare Cabin Embarked
53      0   2926  26.0   NaN        S


     PassengerId  Survived  Pclass                             Name   Sex  \
688          689         0       3  Fischer, Mr. Eberhard Thelander  male

      Age  SibSp  Parch  Ticket    Fare Cabin Embarked
688  18.0      0      0  350036  7.7958   NaN        S


     PassengerId  Survived  Pclass                     Name     Sex  Age  \
306          307         1       1  Fleming, Miss. Margaret  female  NaN

     SibSp  Parch Ticket      Fare Cabin Embarked
306      0      0  17421  110.8833   NaN        C


     PassengerId  Survived  Pclass              Name   Sex  Age  SibSp  Parch  \
428          429         0       3  Flynn, Mr. James  male  NaN      0      0

     Ticket  Fare Cabin Embarked
428  364851  7.75   NaN        Q


     PassengerId  Survived  Pclass             Name   Sex  Age  SibSp  Parch  \
825          826         0       3  Flynn, Mr. John  male  NaN      0      0

     Ticket  Fare Cabin Embarked
825  368323  6.95   NaN        Q


     PassengerId  Survived  Pclass                              Name   Sex  \
572          573         1       1  Flynn, Mr. John Irwin ("Irving")  male

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked
572  36.0      0      0  PC 17474  26.3875   E25        S


     PassengerId  Survived  Pclass             Name   Sex  Age  SibSp  Parch  \
643          644         1       3  Foo, Mr. Choong  male  NaN      0      0

    Ticket     Fare Cabin Embarked
643   1601  56.4958   NaN        S


     PassengerId  Survived  Pclass                                  Name  \
436          437         0       3  Ford, Miss. Doolina Margaret "Daisy"

        Sex   Age  SibSp  Parch      Ticket    Fare Cabin Embarked
436  female  21.0      2      2  W./C. 6608  34.375   NaN        S


     PassengerId  Survived  Pclass                              Name     Sex  \
147          148         0       3  Ford, Miss. Robina Maggie "Ruby"  female

     Age  SibSp  Parch      Ticket    Fare Cabin Embarked
147  9.0      2      2  W./C. 6608  34.375   NaN        S


    PassengerId  Survived  Pclass                    Name   Sex   Age  SibSp  \
86           87         0       3  Ford, Mr. William Neal  male  16.0      1

    Parch      Ticket    Fare Cabin Embarked
86      3  W./C. 6608  34.375   NaN        S


     PassengerId  Survived  Pclass                                     Name  \
736          737         0       3  Ford, Mrs. Edward (Margaret Ann Watson)

        Sex   Age  SibSp  Parch      Ticket    Fare Cabin Embarked
736  female  48.0      1      3  W./C. 6608  34.375   NaN        S


     PassengerId  Survived  Pclass                             Name   Sex  \
452          453         0       1  Foreman, Mr. Benjamin Laventall  male

      Age  SibSp  Parch  Ticket   Fare Cabin Embarked
452  30.0      0      0  113051  27.75  C111        C


     PassengerId  Survived  Pclass                            Name     Sex  \
341          342         1       1  Fortune, Miss. Alice Elizabeth  female

      Age  SibSp  Parch Ticket   Fare        Cabin Embarked
341  24.0      3      2  19950  263.0  C23 C25 C27        S


    PassengerId  Survived  Pclass                        Name     Sex   Age  \
88           89         1       1  Fortune, Miss. Mabel Helen  female  23.0

    SibSp  Parch Ticket   Fare        Cabin Embarked
88      3      2  19950  263.0  C23 C25 C27        S


    PassengerId  Survived  Pclass                            Name   Sex   Age  \
27           28         0       1  Fortune, Mr. Charles Alexander  male  19.0

    SibSp  Parch Ticket   Fare        Cabin Embarked
27      3      2  19950  263.0  C23 C25 C27        S


     PassengerId  Survived  Pclass               Name   Sex   Age  SibSp  \
438          439         0       1  Fortune, Mr. Mark  male  64.0      1

     Parch Ticket   Fare        Cabin Embarked
438      4  19950  263.0  C23 C25 C27        S


     PassengerId  Survived  Pclass                     Name   Sex   Age  \
344          345         0       2  Fox, Mr. Stanley Hubert  male  36.0

     SibSp  Parch  Ticket  Fare Cabin Embarked
344      0      0  229236  13.0   NaN        S


     PassengerId  Survived  Pclass                            Name     Sex  \
309          310         1       1  Francatelli, Miss. Laura Mabel  female

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked
309  30.0      0      0  PC 17485  56.9292   E36        C


     PassengerId  Survived  Pclass                           Name   Sex   Age  \
660          661         1       1  Frauenthal, Dr. Henry William  male  50.0

     SibSp  Parch    Ticket    Fare Cabin Embarked
660      2      0  PC 17611  133.65   NaN        S


     PassengerId  Survived  Pclass  \
334          335         1       1

                                                  Name     Sex  Age  SibSp  \
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female  NaN      1

     Parch    Ticket    Fare Cabin Embarked
334      0  PC 17611  133.65   NaN        S


     PassengerId  Survived  Pclass                                Name  \
539          540         1       1  Frolicher, Miss. Hedwig Margaritha

        Sex   Age  SibSp  Parch Ticket  Fare Cabin Embarked
539  female  22.0      0      2  13568  49.5   B39        C


     PassengerId  Survived  Pclass                              Name   Sex  \
587          588         1       1  Frolicher-Stehli, Mr. Maxmillian  male

      Age  SibSp  Parch Ticket  Fare Cabin Embarked
587  60.0      1      1  13567  79.2   B41        C


     PassengerId  Survived  Pclass                              Name   Sex  \
481          482         0       2  Frost, Mr. Anthony Wood "Archie"  male

     Age  SibSp  Parch  Ticket  Fare Cabin Embarked
481  NaN      0      0  239854   0.0   NaN        S


     PassengerId  Survived  Pclass              Name   Sex  Age  SibSp  Parch  \
815          816         0       1  Fry, Mr. Richard  male  NaN      0      0

     Ticket  Fare Cabin Embarked
815  112058   0.0  B102        S


     PassengerId  Survived  Pclass                       Name     Sex   Age  \
357          358         0       2  Funk, Miss. Annie Clemmer  female  38.0

     SibSp  Parch  Ticket  Fare Cabin Embarked
357      0      0  237671  13.0   NaN        S


     PassengerId  Survived  Pclass                         Name   Sex   Age  \
137          138         0       1  Futrelle, Mr. Jacques Heath  male  37.0

     SibSp  Parch  Ticket  Fare Cabin Embarked
137      1      0  113803  53.1  C123        S


   PassengerId  Survived  Pclass  \
3            4         1       1

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0

   Ticket  Fare Cabin Embarked
3  113803  53.1  C123        S


    PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
20           21         0       2  Fynney, Mr. Joseph J  male  35.0      0

    Parch  Ticket  Fare Cabin Embarked
20      0  239865  26.0   NaN        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
405          406         0       2  Gale, Mr. Shadrach  male  34.0      1

     Parch Ticket  Fare Cabin Embarked
405      0  28664  21.0   NaN        S


     PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
703          704         0       3  Gallagher, Mr. Martin  male  25.0      0

     Parch Ticket    Fare Cabin Embarked
703      0  36864  7.7417   NaN        Q


     PassengerId  Survived  Pclass                Name   Sex  Age  SibSp  \
760          761         0       3  Garfirth, Mr. John  male  NaN      0

     Parch  Ticket  Fare Cabin Embarked
760      0  358585  14.5   NaN        S


     PassengerId  Survived  Pclass                  Name     Sex   Age  SibSp  \
576          577         1       2  Garside, Miss. Ethel  female  34.0      0

     Parch  Ticket  Fare Cabin Embarked
576      0  243880  13.0   NaN        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
791          792         0       2  Gaskell, Mr. Alfred  male  16.0      0

     Parch  Ticket  Fare Cabin Embarked
791      0  239865  26.0   NaN        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
619          620         0       2  Gavey, Mr. Lawrence  male  26.0      0

     Parch Ticket  Fare Cabin Embarked
619      0  31028  10.5   NaN        S


     PassengerId  Survived  Pclass               Name   Sex   Age  SibSp  \
462          463         0       1  Gee, Mr. Arthur H  male  47.0      0


In [ ]:
import pandas as pd
df = pd.read_csv('/scraped_data.csv')

In [ ]:
df.isna().sum()

Country        0
2005 Sales     1
2006 Sales     1
2007 Sales     1
2008 Sales     1
2009 Sales     1
2010 Sales     1
2011 Sales     1
2012 Sales     1
2013 Sales     1
2014 Sales     1
2015 Sales     0
2016 Sales     3
2017 Sales     1
2018 Sales     1
2019 Sales     1
2020 Sales    84
2021 Sales    83
2022 Sales    84
dtype: int64

In [ ]:
df.tail(20)

,Country,2005 Sales,2006 Sales,2007 Sales,2008 Sales,2009 Sales,2010 Sales,2011 Sales,2012 Sales,2013 Sales,2014 Sales,2015 Sales,2016 Sales,2017 Sales,2018 Sales,2019 Sales,2020 Sales,2021 Sales,2022 Sales
121,Qatar,"61,100","59,900","60,500","60,000","40,000","40,000","45,000","60,000","65,000","71,500","69,200","50,200","41,176","38,816","39,679",NaN,NaN,NaN
122,R. of Congo,200,200,200,500,"1,500","1,500","1,500","1,500","1,500","1,500","1,600",NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Senegal,"3,000","3,000","3,000","3,000","4,000","4,000","3,500","4,000","4,000","4,500","3,700","4,400","3,773","3,558","3,320",NaN,NaN,NaN
124,Serbia,"21,603","25,610","32,772","36,177","30,000","28,951","22,181","22,800","23,000","23,900","21,700","23,300","22,090","24,006","25,514",NaN,NaN,NaN
125,Singapore,"109,167","116,849","110,814","100,979","73,183","47,273","33,493","32,724","27,955","32,807","61,512","91,096","94,692","81,625","76,476",NaN,NaN,NaN
126,Slovenia,"59,324","59,578","68,719","71,575","57,967","61,142","60,193","50,091","52,268","53,296","59,450","63,674","62,522","65,115","70,904",NaN,NaN,NaN
127,Sri Lanka,"2,600","2,800","2,900","3,000","3,000","2,000","7,000","8,000","10,000","13,800","12,500","26,300","11,796","10,981","8,100",NaN,NaN,NaN
128,Sudan,"2,000","2,000","2,500","3,000","7,000","2,000","2,000","2,000","1,500","1,800","2,200",NaN,"1,450","1,140",996,NaN,NaN,NaN
129,Syria,"32,985","45,467","36,000","42,000","46,000","78,147","33,160","36,300","35,500","33,400","33,400","33,400","4,500","6,996","11,428",NaN,NaN,NaN
130,Tajikistan,"5,300","5,700","5,800","6,000","7,000","6,500","7,500","6,000","6,000","6,100","6,100","1,900","2,000","2,200","2,200",NaN,NaN,NaN
131,Tanzania,"2,000","2,000","2,000","2,000","2,000","2,000","3,000","3,000","3,500","1,000","2,600","2,300",938,998,675,NaN,NaN,NaN
132,Tr.&Tobago,"10,000","10,000","5,000","10,000","10,000","10,000","10,000","8,000","8,000","6,300","10,500","13,900","9,840","9,712","10,707",NaN,NaN,NaN
133,Tunisia,"25,000","30,000","30,000","33,000","35,000","45,000","35,000","37,000","35,000","37,100","36,100","36,400","45,886","35,343","34,387",NaN,NaN,NaN
134,Turkmenistan,"3,900","4,200","4,300","4,500","4,500","4,500","5,000","4,500","4,500","4,600","4,600","4,500","4,800","5,100","5,225",NaN,NaN,NaN
135,Uganda,"3,000","3,500","3,000","3,000","3,000","3,000","3,000","3,000","3,000","3,000","2,200","2,900",721,770,832,NaN,NaN,NaN
136,Uruguay,"10,000","10,000","12,000","15,000","30,000","40,000","38,308","38,109","41,785","40,171","39,472","35,924","41,549","34,377","30,063",NaN,NaN,NaN
137,Venezuela,"128,601","184,108","267,932","135,882","67,047","68,210","65,339","60,776","43,887","10,400","7,700","3,200","2,500","1,159","3,000",NaN,NaN,NaN
138,Yemen,"4,000","4,700","4,800","5,000","5,000","2,000","2,000","2,000","2,000","2,500","2,300","1,100",828,552,552,NaN,NaN,NaN
139,Zambia,"2,300","2,700","2,800","2,600","3,000","2,000","2,000","2,000","2,000","2,000","1,700","2,300",848,"1,118","1,094",NaN,NaN,NaN
140,Zimbabwe,"7,000","6,000","3,000","3,000","3,000","2,000","3,000","3,000","3,000","4,100","1,500","1,300","1,094",906,532,NaN,NaN,NaN

In [ ]:
merged_df=pd.merge(df.head(2),df.tail(2),how='outer',indicator=True)
merged_df

,Country,2005 Sales,2006 Sales,2007 Sales,2008 Sales,2009 Sales,2010 Sales,2011 Sales,2012 Sales,2013 Sales,2014 Sales,2015 Sales,2016 Sales,2017 Sales,2018 Sales,2019 Sales,2020 Sales,2021 Sales,2022 Sales,_merge
0,China,"3,971,101","5,175,961","6,297,538","6,755,609","10,331,315","13,757,794","14,472,416","15,495,240","17,927,730","19,707,677","21,210,339","24,376,902","24,718,321","23,709,782","21,472,092","20,177,731","21,481,537","23,563,287",left_only
1,India,"1,106,863","1,311,373","1,511,812","1,545,414","1,816,878","2,387,197","2,510,313","2,781,919","2,553,979","2,570,736","2,772,270","2,966,637","3,229,109","3,394,756","2,962,115","2,433,464","3,082,279","3,792,356",left_only
2,Zambia,"2,300","2,700","2,800","2,600","3,000","2,000","2,000","2,000","2,000","2,000","1,700","2,300",848,"1,118","1,094",NaN,NaN,NaN,right_only
3,Zimbabwe,"7,000","6,000","3,000","3,000","3,000","2,000","3,000","3,000","3,000","4,100","1,500","1,300","1,094",906,532,NaN,NaN,NaN,right_only